@startuml
hide footbox

' Participants

participant "zeppelin" as Notebook
participant "spark-plugin" as SparkPlugin
participant "spark-service" as SparkService
participant "catalog-service" as CatalogService
participant "auth-service" as AuthService
participant "dlp-secret-service" as SecretService
database "GCS" as GCS

' Write (and pseudonymize) data
note left of SparkPlugin
    ns='/path/to/data'
    options={
        pseudo: "col1=func1-123,col2=func2-456"
    }
end note

Notebook->SparkPlugin: write(ns, options)

SparkPlugin->SparkService:

activate SparkService
SparkService->CatalogService: getMetadata(ns)
CatalogService-->SparkService: (dataLocation, valuation, state, pseudoConfig, etc)
SparkService->AuthService: canAccess(ns, options)
AuthService-->SparkService:
SparkService-->SecretService: getPseudoKeys()
SecretService-->SparkService:
SparkService-->SparkPlugin
deactivate SparkService

SparkPlugin->SparkPlugin: pseudoContext.apply(data)

SparkPlugin->GCS: write data
activate GCS
GCS-->SparkPlugin:
deactivate GCS
SparkPlugin->SparkService:
activate SparkService
SparkService->CatalogService: createOrUpdate
SparkService-->SparkPlugin
deactivate SparkService
SparkPlugin-->Notebook
====

' Read depseudonymized data

note left of SparkPlugin
    ns='/path/to/data'
    options={pseudo=all}
end note

Notebook->SparkPlugin: read(ns, options)
SparkPlugin->SparkService:
activate SparkService
SparkService->CatalogService: getMetadata(ns)
CatalogService-->SparkService: (dataLocation, valuation, state, pseudoConfig, etc)
SparkService->AuthService: canAccess(ns, options)
AuthService-->SparkService:
SparkService-->SecretService: getPseudoKeys()
SecretService-->SparkService:
SparkService-->SparkPlugin:
deactivate SparkService

activate SparkPlugin
SparkPlugin->GCS: loadData(dataLocation)
GCS->SparkPlugin: dataframe

SparkPlugin->SparkPlugin: pseudoContext.restore(data)
SparkPlugin-->Notebook

@enduml